# Generated by Django 2.2.1 on 2020-03-19 13:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import mesika_utils.RandomTransactionIds


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(default=mesika_utils.RandomTransactionIds.generate_sso_token, max_length=250, primary_key=True, serialize=False, unique=True)),
                ('mesika_reference_number', models.CharField(default=mesika_utils.RandomTransactionIds.generate_sso_token, max_length=250, unique=True)),
                ('payer_msisdn', models.CharField(blank=True, max_length=210, null=True)),
                ('payer_reference_number', models.CharField(max_length=250, unique=True)),
                ('account_number', models.CharField(max_length=210)),
                ('amount', models.DecimalField(decimal_places=2, default=0.01, max_digits=100)),
                ('processing_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('provider', models.CharField(default='MTN MOBILE MONEY', max_length=210)),
                ('provider_reference_number', models.CharField(default=mesika_utils.RandomTransactionIds.generate_sso_token, max_length=250, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('SUCCESSFUL', 'SUCCESSFUL')], default='PENDING', max_length=50)),
                ('status_description', models.CharField(blank=True, max_length=250, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transactions',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jobs_id', models.CharField(default=mesika_utils.RandomTransactionIds.generate_sso_token, max_length=210, primary_key=True, serialize=False, unique=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Transactions')),
            ],
            options={
                'verbose_name': 'Jobs',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='ExtraDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Transactions')),
            ],
            options={
                'verbose_name': 'ExtraDetails',
                'verbose_name_plural': 'ExtraDetails',
            },
        ),
    ]
